"""add product des

Revision ID: 201c3b7c9b9b
Revises: 
Create Date: 2021-04-04 17:29:50.493022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201c3b7c9b9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_des', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_des')
    # ### end Alembic commands ###
